name: Nightwatch Tests

on: [push, pull_request]

jobs:
  test-and-log-errors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # Updated to Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Start backend service
      run: |
        node index.js &
        sleep 5

    - name: Run Nightwatch tests
      id: nightwatch
      run: |
        npx nightwatch || echo "Tests failed" > error.log

    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: error-log
        path: error.log

    - name: Log errors to GitHub
      if: failure()
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [ -f error.log ]; then
          ERROR_LOG=$(cat error.log)
          ISSUE_BODY="### Test failure detected\n\`\`\`\n$ERROR_LOG\n\`\`\`"
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\": \"Automated Test Failure: $(date +'%Y-%m-%d %H:%M:%S')\", \"body\": \"$ISSUE_BODY\"}"
        fi
